### PR TITLE
Add support to 1.6

### PR DESCRIPTION
**Pull request by gerardorochin**
https://www.elastic.co/blog/elasticsearch-1-6-0-released

### CODE REVIEW

**Comment by tianon** [comment]
Any reason you closed?  I can take over if you'd like -- either way, we definitely want 1.6! :+1:

**Comment by tianon** [comment]
LGTM

**Comment by gerardorochin** [comment]
He had forgotten to change java 8 haha :dancers:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
