### PR TITLE
Workdir most the things

### PR DESCRIPTION
**Pull request by webwurst**
Fixes docker-library/elasticsearch#87

/ping @tianon

### CODE REVIEW

**Comment by rodriguezsergio** [comment]
:+1:

**Comment by tianon** [comment]
Arg, thanks @webwurst :disappointed:

LGTM

**Comment by rodriguezsergio** [comment]
When does this get merged into docker hub?

**Comment by yosifkit** [comment]
Tis building on the official server right now: https://github.com/docker-library/official-images/issues/1532.

**Pull request merged**
