### PR TITLE
Minimize docker diff after container run

### PR DESCRIPTION
**Pull request by md5**
* Exposes a volume at `/usr/share/elasticsearch/data`
* Updates `logging.yml` to remove `file`, `index_search_slow_log_file`, and `index_indexing_slow_log_file` appenders

### CODE REVIEW

**Comment by tianon** [comment]
:+1: @Moghedrin review review

**Comment by Moghedrin** [comment]
At current, those default config files are being downloaded via the update script, so the changes in `logging.yml` will be wiped away the minute we need to update. I'm definitely open to the idea of *not* doing it this way, and providing just some static configs, but you'll have to make a change in `update.sh` to reflect that. :)

Other than that, :+1:

**Comment by Moghedrin** [comment]
@md5 @tianon Once we get this tied up, I'll make the pull request to get this and the docs included into the official images.

**Comment by tianon** [comment]
@md5 if you're willing to help maintain at least the configs (or the whole image, since you seem very interested in it), I'd be +1 on adding your name in the `# maintainer:` comments in the library file if @Moghedrin is down with that too :wink:

**Comment by Moghedrin** [comment]
Hella down with that idea.

**Comment by md5** [comment]
:blush: 

Do you guys want to stick with the approach of extracting `config` from the tarball and amend it to disable the file-based appenders? Or would it be better to just start maintaining `logging.yml` directly? (`elasticsearch.yml` is currently all comments, so it could probably be dispensed with)

**Comment by tianon** [comment]
I'm +1 on just maintaining it, especially if it isn't likely to change much
in future releases.

(especially since I hate how slow "update.sh" is now)

**Comment by md5** [comment]
OK. I removed the config extraction from `update.sh`. I also removed the `elasticsearch.yml` since it was all comments.

I just took a look at the docs diff and I'd probably change the examples to use `-d`. We should probably also document the fact that the image uses a volume at `/usr/share/elasticsearch/data`.

Should I send a PR to the infosiftr repo for that or do you guys just want to make the updates?

**Comment by md5** [comment]
I took the liberty of updating the docs: https://github.com/md5/docker-library-docs/compare/infosiftr:elasticsearch-docs...elasticsearch-docs

**Comment by Moghedrin** [comment]
LGTM! Merging this in, then submitting pull request to the official images. :)

**Pull request merged**
