### PR TITLE
Update generate script

### PR DESCRIPTION
**Pull request by tianon**
```console
$ ./generate-stackbrew-library.sh
# maintainer: InfoSiftr <github@infosiftr.com> (@infosiftr)

1.3.7: git://github.com/docker-library/elasticsearch@2fe2cb3aa293a0e75ebc1f72d27cf1aad73d21cb 1.3
1.3: git://github.com/docker-library/elasticsearch@2fe2cb3aa293a0e75ebc1f72d27cf1aad73d21cb 1.3

1.4.2: git://github.com/docker-library/elasticsearch@2fe2cb3aa293a0e75ebc1f72d27cf1aad73d21cb 1.4
1.4: git://github.com/docker-library/elasticsearch@2fe2cb3aa293a0e75ebc1f72d27cf1aad73d21cb 1.4
1: git://github.com/docker-library/elasticsearch@2fe2cb3aa293a0e75ebc1f72d27cf1aad73d21cb 1.4
latest: git://github.com/docker-library/elasticsearch@2fe2cb3aa293a0e75ebc1f72d27cf1aad73d21cb 1.4
```

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
ping @Moghedrin

**Comment by tianon** [comment]
You also appear to be pushing to `infosiftr/master` still (which is why I've got one of your commits here).

**Comment by Moghedrin** [comment]
LGTM. And my bad. Embarrassingly, I thought I was still working in
`infosiftr/elasticsearch`, rather than here. I didn't even realize we had a
repo for this in `docker-library` yet. It's going to be a long day. /sigh

**Comment by tianon** [comment]
I have a Monster in my fridge here, but you'll have to drive two hours to get it... :heart:

**Comment by Moghedrin** [comment]
You should probably just throw that away. It's -literally- been there for
over a year and a half.

**Pull request merged**
