### PR TITLE
Make the privilege drop down optional

### LINKED ISSUE #5: Run as user "elasticsearch"
The `elasticsearch` package that is being installed for this image creates an "`elasticsearch`" user that is used by the `init.d` script:

    $ docker run --rm elasticsearch:1.4 id elasticsearch
    uid=105(elasticsearch) gid=108(elasticsearch) groups=108(elasticsearch)

This user is not being utilitized in the `/usr/share/elasticsearch/bin/elasticsearch` script, which means this image is currently running the ES service as `root`.

The image should be updated so that the service does not run as `root`. Since ES doesn't appear to have its own way to drop privileges, it seems like that way to go here is with `gosu` and a custom `ENTRYPOINT`.

### PR DESCRIPTION
**Pull request by ggtools**
As in some situation, it is impossible to execute `chown` on the
data directory running elasticsearch as the `elasticsearch` user is
not possible. The entry point now supports to run elasticsearch
as `root` if the `RUN_AS_ROOT` environment variable is set to a non
empty string.

Fixes #5

### CODE REVIEW

**Comment by md5** [comment]
How about having `: ${ELASTICSEARCH_USER:=elasticsearch}` instead of `RUN_AS_ROOT`?

**Comment by md5** [comment]
That would imply changing the `chown` and `gosu` commands to use `$ELASTICSEARCH_USER` and skipping them when `"$ELASTICSEARCH_USER" = root`.

**Comment by ggtools** [comment]
Yes I thought of this but then I looked at the `chown elasticsearch:elasticsearch` and I did wonder if I wanted to replace it by:

- `chown $ELASTICSEARCH_USER:elasticsearch`
- `chown $ELASTICSEARCH_USER:$ELASTICSEARCH_USER`
- `chown $ELASTICSEARCH_USER`
- or find the primary group of `$ELASTICSEARCH_USER` and using it

**Comment by yosifkit** [comment]
A user might want to make the ability to tack on the group; `-e ELASTICSEARCH_USER='1000:50'` would be the common option.

**Comment by ggtools** [comment]
Love this @yosifkit so the test would be to check if the user part is `root`

**Comment by yosifkit** [comment]
Seems it would also need to check if someone decided to put `0` for root as well.

**Comment by ggtools** [comment]
Yup. So working on it ...

**Comment by md5** [comment]
Not to complicate things, but `ELASTICSEARCH_GROUP` might be clearer.

**Comment by md5** [comment]
I also just thought about the fact that there will be some inconsistency across the official images in the use of `*_USER` variables. In the case of `postgres`, the `POSTGRES_USER` variable refers to a DB-level user, not a Unix user.

**Comment by yosifkit** [comment]
I am thinking this change can apply for all "data/server" images (ex: mysql, mongo, elasticsearch, redis, memcached...), so I would like to have it just as `-e RUN_AS user:group`.  That way it is consistent on all the images.

**Comment by ggtools** [comment]
That's why `RUN_AS_XXX` might be a little be clearer

**Comment by md5** [comment]
:+1:

**Comment by yosifkit** [comment]
Quick wrench to throw in, would the `RUN_AS` only apply for running the contained software (in this case elasticsearch) or would it also apply if I run something else in the container (ex: `docker run -it --rm -e RUN_AS='999' elasticsearch bash`)?   I can easily see users get confused either way and we will need to be sure to document it.

**Comment by ggtools** [comment]
Hmmm interesting ... current it would only apply to elasticsearch, not other commands. I can see your point however one goals of the entry point script was to run elasticsearch with the correct user and then give a bypass for everything else. Since the command would be executed directly you should probably resort to the normal docker mechanism and use `-u 999` if you don't want your command to be run as root

**Comment by yosifkit** [comment]
That is what I was thinking, if they really need to be another user they are root and have `gosu` or `su`.  We just need to make sure users know that the ENV only applies to running the contained software and that actions like bash will run as root.

**Comment by ggtools** [comment]
And *voilà*

**Comment by md5** [comment]
LGTM

**Comment by tianon** [comment]
Here's my thoughts on this:
- `RUN_AS` is a _really_ generic name; more generic than any environment variable we've used in any official image thus far -- my concern with that is people will start thinking it applies in more places than it does, and either wondering why it isn't working or even worse not even noticing that it's not working and thinking that it is
- `chown` and `gosu` accept the same syntax for their arguments -- `user`, `uid`, `user:group`, `uid:gid`, `user:gid`, `uid:group` are all reasonable and acceptable for both, so _if_ we do this, having two knobs for it seems like overkill IMO

**Comment by ggtools** [comment]
I mostly agree with both items however for the first one I don't have any idea of a replacement name.

**Comment by ei-grad** [comment]
Isn't the docker run --user option made for this?.. Using gosu to drop priveledges is absolutely useless ugly hack. And making chown for all data on the provided volume is a very bad thing, too.

**Comment by tianon** [comment]
Without the chown, the user we switch to isn't able to write to the
directory.

**Comment by ei-grad** [comment]
It is not the problem, as it could (and should) be easily fixed by user. If he really need to chown. But the `--user` flag makes it possible to don't make chown at all.

**Comment by tianon** [comment]
Ok, so what does the user chown to?  The username inside the container may
not even exist on the host (and if it does, it's not very likely to match
UID/GID), so it's going to have to be an arbitrary UID/GID combination,
which is very much the opposite of user-friendly.

**Comment by ggtools** [comment]
I can add some support to make the script work when the container is launched with a `--user` option but I'm pretty sure the chown and drop privileges thing is probably the easiest way for the user especially in the future when Docker will use the user namespace which will make quite hard to make the `chown` to the right user from outside the container

**Comment by nizsheanez** [comment]
Guys, what is the right way to start elasticsearch:2 for now? 
I using Docker Toolbox for Mac

With `--user `:
```
docker run --user elasticsearch -it -v $(pwd)/es/data:/usr/share/elasticsearch/data -v $(pwd)/es/config:/usr/share/elasticsearch/config elasticsearch
error: failed switching to "elasticsearch": setgroups operation not permitted
```

Without `--user`:
```
docker run -it -v $(pwd)/es/data:/usr/share/elasticsearch/data -v $(pwd)/es/config:/usr/share/elasticsearch/config elasticsearch
Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
```

**Comment by TakenPilot** [comment]
*bump*  Seems this thread was abandoned, but the issue is still real.

**Comment by yosifkit** [comment]
After some discussion offline with @tianon, we are thinking that the best course of action is to gracefully skip operations that require root when the container is not run as root for all official images (as far as is possible). This will allow you to run with `--user`, but you would be responsible to `chown/chmod` any files and directories that the process needs.

So, something like: 
```bash
if [ "$(id -u)" = '0' ]; then
    chown ...
    set -- gosu ...
fi

exec "$@"
```

**Pull request closed without merging**
