### PR TITLE
Fix the pattern match for the update script.

### PR DESCRIPTION
**Pull request by Moghedrin**
Fixes issue noted by @yosifkit.

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by yosifkit** [comment]
ping @tianon

**Comment by tianon** [comment]
You missed the other half of this, but I think this regex could also be a little simpler if we used a different delimiter too:
```bash
sed -rn 's!.*?http://www.elasticsearch.org/downloads/[0-9]+-[0-9]+-[0-9]+/">Download v ([0-9]+\.[0-9]+\.[0-9]+)<.*!\1!gp'
```

**Comment by Moghedrin** [comment]
Wow. That's embarrassing. I didn't even see that first one.

**Comment by Moghedrin** [comment]
ping @tianon

**Comment by tianon** [comment]
LGTM

**Pull request merged**
