### PR TITLE
Remove unused environment variable ELASTICSEARCH_MAJOR

### PR DESCRIPTION
**Pull request by antonbormotov**

### CODE REVIEW

**Comment by antonbormotov** [comment]
Anyone from maintainers, how do I fix failing build?

**Comment by tianon** [comment]
Failure on 5.0 is unfortunately expected (#98). :sob:

This change will need to be made in `Dockerfile.template` though: https://github.com/docker-library/elasticsearch/blob/667407333e51a2d1f2e12a76792fcfbdeb5d79ba/Dockerfile.template#L19 :+1:

**Comment by antonbormotov** [comment]
I removed from template and ran: `./update.sh 1.5 1.6 1.7 2.0 2.1 2.2 2.3 5.0`

**Comment by tianon** [comment]
Merged manually via 2bfa452 :+1:

Thanks!

**Pull request closed without merging**
