### PR TITLE
Bump Elasticsearch version to 1.5.1

### PR DESCRIPTION
**Pull request by tristan0x**
New version of Elasticsearch has been released today.

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by tianon** [comment]
LGTM

**Comment by tristan0x** [comment]
Thank you @tianon. Is there something I have to do so that Docker Hub gets updated accordingly?

**Comment by yosifkit** [comment]
Once PR's like this merge we do a PR to the `docker-library/official-images` to update the `library/` file with the new commit hashes and versions as needed (using the `generate-stackbrew-library.sh`).  There are a couple that need updating, so I was just about to do one.

**Pull request merged**
