### PR TITLE
Add extensionpoint to docker-entrypoint.sh

### PR DESCRIPTION
**Pull request by sebglon**
Add scan folder docker-entrypoint-initels.d to extend container before every start up CMD 
show docker-library/elasticsearch#85

### CODE REVIEW

**Comment by czerasz** [comment]
This would be very useful. For example for adding mapping templates or creating indexes with a specific mapping.

**Comment by tianon** [comment]
I think the discussion in https://github.com/docker-library/mongo/pull/53 is very relevant here.

**Comment by tianon** [comment]
Arg, I linked to the wrong discussion, sorry. :disappointed:

Relevant comments/discussion:
- https://github.com/docker-library/cassandra/issues/31#issuecomment-153197665
- https://github.com/docker-library/rabbitmq/pull/53#issuecomment-162618292

**Comment by yosifkit** [comment]
My thought for this one specifically is why not just end my custom script with `exec /docker-entrypoint.sh elasticsearch` and then run my container with the following:

```console
$ docker run -d -v /custom/script.sh:/custom-script.sh elasticsearch /custom-script.sh
```

The only thing we miss inheriting from the entrypoint into our script is the `chown` beforehand and the stepdown from root, which could be a bonus.  If we really want to not be root, we can just add `--user elasticsearch` to the docker run and we get basically the same setup as the PR.

The reason I bring this up is that `docker-entrypoint-initdb.d` exists in images like postgres to let you do things that can only be done after the database files are initialized and while the database is running.  Whereas I don't see that in this PR, since elasticsearch is not running and doesn't require initialization.

For example, I can do the following and have my plugin in the resulting image:
```Dockerfile
FROM elasticsearch
RUN plugin -i elasticsearch/marvel/latest
```

**Comment by mi-hol** [comment]
@sebglon I wonder if @yosifkit proposed solution solved your issue? In case it did this could be closed :)

**Comment by zerthimon** [comment]
So, what @yosifkit proposed actually works well.
I've made this little custom script to install x-pack
```
#!/bin/bash

# install x-pack if not yet installed
if ! bin/elasticsearch-plugin list | grep -qs x-pack; then
   yes | bin/elasticsearch-plugin install x-pack
fi

# run elastic
exec /docker-entrypoint.sh elasticsearch "$@"
```

**Comment by kdh6429** [comment]
Not operating in master yet? I made some shell script in 'docker-entrypoint-initels.d' but seems not executed.

**Comment by kdh6429** [comment]
I would like to set templates from docker-compose, and to do this, it require elasticsearch running.

**Comment by yosifkit** [comment]
Closing since the repo is being deprecated.  See discussion on #160 for more information.

> This image is officially deprecated in favor of [the `elasticsearch` image provided by elastic.co](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) which is available to pull via `docker.elastic.co/elasticsearch/elasticsearch:[version]` like `5.2.1`. This image will receive no further updates after 2017-06-20 (June 20, 2017). Please adjust your usage accordingly.
>
>Elastic provides open-source support for Elasticsearch via the [elastic/elasticsearch GitHub repository](https://github.com/elastic/elasticsearch) and the Docker image via the [elastic/elasticsearch-docker GitHub repository](https://github.com/elastic/elasticsearch-docker), as well as community support via its [forums](https://discuss.elastic.co/c/elasticsearch).

**Pull request closed without merging**
