### PR TITLE
sed executable overridable using SED environment variable.

### PR DESCRIPTION
**Pull request by tristan0x**
BSD sed does not support _-r_ option. Thanks to this PR I can use the following command to run `update.sh`:

```
SED=gsed ./update.sh
```

### CODE REVIEW

**Comment by md5** [comment]
`readlink -f` is also a GNU-ism, so this only partially fixes the problem of running `update.sh` on non-GNU systems.

**Comment by md5** [comment]
Also, see #12

**Comment by tristan0x** [comment]
Hi ~~sha1~~ @md5 :)
Here is a new patch that gets rid of `readlink` and `dirname`.

**Comment by md5** [comment]
:unamused:

**Comment by md5** [comment]
Not sure how @tianon will feel about ditching `readlink` entirely, but it's probably safe enough for how most people run the script.

**Comment by ggtools** [comment]
I kinda like the auto detection, albeit only working for MacOSX, I implemented in #12

**Comment by tianon** [comment]
Closing given that update.sh is now run automatically by @docker-library-bot. :+1:

**Pull request closed without merging**
